name: frontend_flutter
description: A Flutter frontend app for adding and viewing items with authentication.
publish_to: 'none' # since this is a local project

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  dio: ^5.3.2
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
